[package]
name = "i3-pretty-tree"
version = "0.1.0"
authors = ["SÃ¶nke Hahn <soenkehahn@gmail.com>"]
edition = "2018"

[dependencies]
i3ipc = { git = "https://github.com/soenkehahn/i3ipc-rs", rev = "75ccae0" }
unicode-segmentation = "*"
